import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import SplashWrapper from "./splashWrapper";
import Nav from "@/components/Nav";
import FadeIn from "@/components/motion/FadeIn";
import TopSection from "@/components/topSection";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          {/* <SplashWrapper>{children}</SplashWrapper> */}
          <FadeIn>
            <div className="flex fixed top-[13px] left-1/2 transform -translate-x-1/2 z-10">
              <Nav />
            </div>
          </FadeIn>
          <TopSection />

          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
